### ISSUE TITLE
notary password

### ISSUE THREAD

**Issue by rodneytamblyn** [trevordevore/levurehelper-macos_notary#4]
Trevor, can I just confirm the password required is the App Specific password described in heading 1.3 of https://lessons.livecode.com/m/4071/l/1122100-codesigning-and-notarizing-your-lc-standalone-for-distribution-outside-the-mac-appstore

**Comment by trevordevore** [comment]
@rodneytamblyn that sounds right. I’m not able to verify that for sure though.

**Comment by rodneytamblyn** [comment]
Confirming that password is the app-specific password created (per the lesson).  Another important note is that the macos_notary_username is your Apple developer login email address

**Comment by trevordevore** [comment]
Closed by #5
